#CREACION DE SCHEMA----------------
CREATE database CAMELLO;
use CAMELLO;
#CREACION DE TABLAS-----------------
CREATE TABLE PERSONA
(
COD_PERSONA integer,
NOMBRES text,
APELLIDOS text,
FECHA_NACIMIENTO text,
FOTO blob,
RUTA_FOTO text,
CORREO text,
CLAVE text,
TELEFONO text,
HOJA_DE_VIDA text
);

CREATE TABLE EMPRESA
(
COD_EMPRESA integer,
COD_C_LABORAL integer,
NOM_EMPRESA text,
LOGO blob,
RUTA_LOGO text,
CORREO text,
CLAVE text,
TELEFONO text,
DESCRIPCION text
);

CREATE TABLE CAMPO_LABORAL
(
COD_C_LABORAL integer,
NOM_C_LABORAL text
);

CREATE TABLE AMIGOS
(
COD_PERSONA integer,
COD_AMIGO integer
);

CREATE TABLE MENSAJE
(
COD_MENSAJE integer,
COD_PERSONA integer,
COD_AMIGO integer,
MENSAJE text);

CREATE TABLE CIUDAD
(
COD_CIUDAD integer,
COD_PAIS integer,
NOM_CIUDAD text);

CREATE TABLE PAIS
(
COD_PAIS integer,
NOM_PAIS text
);

CREATE TABLE PUBLICAR_PERSONA
(
COD_P_PERSONA integer,
COD_PERSONA integer,
COD_CIUDAD integer,
DETALLE_PUBLICACION text,
FECHA date);

CREATE TABLE PUBLICAR_EMPRESA
(
COD_P_EMPRESA integer,
COD_EMPRESA integer,
COD_CIUDAD integer,
COD_JORNADA integer,
COD_CARGO integer,
COD_SALARIO integer,
DETALLE_PUBLICACION text,
EXPERIENCIA_REQUERIDA text,
FECHA date);

CREATE TABLE SALARIO
(COD_SALARIO integer,
SALARIO text
);

CREATE TABLE CARGO
(
COD_CARGO integer,
NOM_CARGO text
); 


CREATE TABLE JORNADA
(
COD_JORNADA integer,
NOM_JORNADA text
);

CREATE TABLE POSTULADOS
(
COD_P_EMPRESA integer,
COD_PERSONA integer,
ESTADO_POSTULADO integer,
ESTADO_ENVIO integer
);
#ADICIONAR LLAVES PRIMARIAS---------------
ALTER TABLE MENSAJE
ADD constraint MENSAJE_PK primary key(COD_MENSAJE);

ALTER TABLE AMIGOS
ADD constraint AMIGOS_PK primary key(COD_PERSONA,COD_AMIGO);

ALTER TABLE PERSONA
ADD constraint PERSONA_PK primary key(COD_PERSONA);

ALTER TABLE EMPRESA
ADD constraint EMPRESA_PK primary key(COD_EMPRESA);

ALTER TABLE CAMPO_LABORAL
ADD constraint CAMPO_LABORAL_PK primary key(COD_C_LABORAL);

ALTER TABLE PUBLICAR_PERSONA
ADD constraint PUBLICAR_PERSONA_PK primary key(COD_P_PERSONA);

ALTER TABLE CARGO
ADD constraint CARGO_PK primary key (COD_CARGO);

ALTER TABLE PUBLICAR_EMPRESA
ADD constraint PUBLICAR_EMPRESA_PK primary key(COD_P_EMPRESA);

ALTER TABLE SALARIO
ADD constraint SALARIO_PK primary key(COD_SALARIO);

ALTER TABLE JORNADA
ADD constraint JORNADA_PK primary key(COD_JORNADA);

ALTER TABLE CIUDAD
ADD constraint CIUDAD_PK primary key(COD_CIUDAD);

ALTER TABLE PAIS
ADD constraint PAIS_PK primary key(COD_PAIS);

ALTER TABLE POSTULADOS
ADD constraint POSTULADOS_PK primary key(COD_P_EMPRESA,COD_PERSONA);

#ADICIONAR LLAVES FORANEAS-------------------

ALTER TABLE EMPRESA
ADD constraint EMPRESA_CAMPO_LABORAL_FK foreign key(COD_C_LABORAL)
references CAMPO_LABORAL(COD_C_LABORAL);

ALTER TABLE CIUDAD
ADD constraint CIUDAD_PAIS_FK foreign key(COD_PAIS)
references PAIS(COD_PAIS);

ALTER TABLE PUBLICAR_PERSONA
ADD constraint PUBLICAR_PERSONA_PERSONA_FK foreign key(COD_PERSONA)
references PERSONA(COD_PERSONA);

ALTER TABLE PUBLICAR_PERSONA
ADD constraint PUBLICAR_PERSONA_CIUDAD_FK foreign key(COD_CIUDAD)
references CIUDAD(COD_CIUDAD);

ALTER TABLE PUBLICAR_EMPRESA
ADD constraint PUBLICAR_EMPRESA_EMPRESA_FK foreign key(COD_EMPRESA)
references EMPRESA(COD_EMPRESA);

ALTER TABLE PUBLICAR_EMPRESA
ADD constraint PUBLICAR_EMPRESA_CIUDAD_FK foreign key(COD_CIUDAD)
references CIUDAD(COD_CIUDAD);

ALTER TABLE PUBLICAR_EMPRESA
ADD constraint PUBLICAR_EMPRESA_JORNADA_FK foreign key(COD_JORNADA)
references JORNADA(COD_JORNADA);

ALTER TABLE PUBLICAR_EMPRESA
ADD constraint PUBLICAR_EMPRESA_CARGO_FK foreign key(COD_CARGO)
references CARGO(COD_CARGO);

ALTER TABLE PUBLICAR_EMPRESA
ADD constraint PUBLICAR_EMPRESA_SALARIO_FK foreign key(COD_SALARIO)
references SALARIO(COD_SALARIO);

ALTER TABLE MENSAJE
ADD constraint MENSAJE_PERSONA_FK foreign key(COD_PERSONA)
references PERSONA(COD_PERSONA);

/*ALTER TABLE MENSAJE
ADD constraint MENSAJE_AMIGOS_FK foreign key(COD_AMIGO)
references AMIGOS(COD_AMIGO);*/

ALTER TABLE AMIGOS
ADD constraint AMIGOS_PERSONA_FK foreign key(COD_PERSONA)
references PERSONA(COD_PERSONA);

ALTER TABLE POSTULADOS
ADD constraint POSTULADOS_PERSONA_FK foreign key(COD_PERSONA)
references PERSONA(COD_PERSONA);

ALTER TABLE POSTULADOS
ADD constraint POSTULADOS_PIBLICAR_EMPRESA_FK foreign key(COD_P_EMPRESA)
references PUBLICAR_EMPRESA(COD_P_EMPRESA);