#CREACION DE SCHEMA----------------
#CREATE database CAMELLO;
#CREATE database CAMELLO;
#use CAMELLO;
#CREACION DE TABLAS-----------------
CREATE TABLE PERSONA
(
COD_PERSONA integer,
NOMBRES text,
APELLIDOS text,
FECHA_NACIMIENTO date,
FOTO blob,
RUTA_FOTO text,
CORREO text,
CLAVE text,
TELEFONO text,
HOJA_DE_VIDA text
);

CREATE TABLE INTERESES_LABORALES
(
COD_I_LABORAL integer,
COD_PERSONA integer,
NOM_I_LABORAL text
);

CREATE TABLE EMPRESA
(
COD_EMPRESA integer,
COD_C_LABORAL integer,
NOM_EMPRESA text,
LOGO blob,
RUTA_LOGO text,
CORREO text,
CLAVE text,
TELEFONO text,
DESCRIPCION text
);

CREATE TABLE CAMPO_LABORAL
(
COD_C_LABORAL integer,
NOM_C_LABORAL text
);
CREATE TABLE EMPLEADOS
(
COD_EMPRESA integer,
COD_PERSONA integer
);

CREATE TABLE AMIGOS
(
COD_PERSONA integer,
COD_AMIGO integer
);

CREATE TABLE MENSAJE
(
COD_MENSAJE integer,
COD_PERSONA integer,
COD_AMIGO integer,
MENSAJE text);

CREATE TABLE CIUDAD
(
COD_CIUDAD integer,
COD_PAIS integer,
NOM_CIUDAD text);

CREATE TABLE PAIS
(
COD_PAIS integer,
NOM_PAIS text
);

CREATE TABLE PUBLICAR_PERSONA
(
COD_P_PERSONA integer,
COD_PERSONA integer,
COD_CIUDAD integer,
DETALLE_PUBLICACION text,
FECHA date);

CREATE TABLE PUBLICAR_EMPRESA
(
COD_P_EMPRESA integer,
COD_EMPRESA integer,
COD_CIUDAD integer,
COD_JORNADA integer,
DETALLE_PUBLICACION text,
CARGO text,
EXPERIENCIA_REQUERIDA text,
FECHA date);

CREATE TABLE JORNADA
(
COD_JORNADA integer,
NOM_JORNADA text
);
#ADICIONAR LLAVES PRIMARIAS---------------
ALTER TABLE MENSAJE
ADD constraint MENSAJE_PK primary key(COD_MENSAJE);

ALTER TABLE AMIGOS
ADD constraint AMIGOS_PK primary key(COD_PERSONA,COD_AMIGO);

ALTER TABLE PERSONA
ADD constraint PERSONA_PK primary key(COD_PERSONA);

ALTER TABLE INTERESES_LABORALES
ADD constraint INTERESES_LABORALES_PK primary key(COD_I_LABORAL);

ALTER TABLE EMPRESA
ADD constraint EMPRESA_PK primary key(COD_EMPRESA);

ALTER TABLE CAMPO_LABORAL
ADD constraint CAMPO_LABORAL_PK primary key(COD_C_LABORAL);

ALTER TABLE EMPLEADOS
ADD constraint EMPLEADOS_PK primary key(COD_EMPRESA,COD_PERSONA);

ALTER TABLE PUBLICAR_PERSONA
ADD constraint PUBLICAR_PERSONA_PK primary key(COD_P_PERSONA);

ALTER TABLE PUBLICAR_EMPRESA
ADD constraint PUBLICAR_EMPRESA_PK primary key(COD_P_EMPRESA);

ALTER TABLE JORNADA
ADD constraint JORNADA_PK primary key(COD_JORNADA);

ALTER TABLE CIUDAD
ADD constraint CIUDAD_PK primary key(COD_CIUDAD);

ALTER TABLE PAIS
ADD constraint PAIS_PK primary key(COD_PAIS);

#ADICIONAR LLAVES FORANEAS-------------------

ALTER TABLE EMPRESA
ADD constraint EMPRESA_CAMPO_LABORAL_FK foreign key(COD_C_LABORAL)
references CAMPO_LABORAL(COD_C_LABORAL);

ALTER TABLE CIUDAD
ADD constraint CIUDAD_PAIS_FK foreign key(COD_PAIS)
references PAIS(COD_PAIS);

ALTER TABLE PUBLICAR_PERSONA
ADD constraint PUBLICAR_PERSONA_PERSONA_FK foreign key(COD_PERSONA)
references PERSONA(COD_PERSONA);

ALTER TABLE PUBLICAR_PERSONA
ADD constraint PUBLICAR_PERSONA_CIUDAD_FK foreign key(COD_CIUDAD)
references CIUDAD(COD_CIUDAD);

ALTER TABLE PUBLICAR_EMPRESA
ADD constraint PUBLICAR_EMPRESA_EMPRESA_FK foreign key(COD_EMPRESA)
references EMPRESA(COD_EMPRESA);

ALTER TABLE PUBLICAR_EMPRESA
ADD constraint PUBLICAR_EMPRESA_CIUDAD_FK foreign key(COD_CIUDAD)
references CIUDAD(COD_CIUDAD);

ALTER TABLE PUBLICAR_EMPRESA
ADD constraint PUBLICAR_EMPRESA_JORNADA_FK foreign key(COD_JORNADA)
references JORNADA(COD_JORNADA);

ALTER TABLE EMPLEADOS
ADD constraint EMPLEADOS_EMPRESA_FK foreign key(COD_EMPRESA)
references EMPRESA(COD_EMPRESA);

ALTER TABLE EMPLEADOS
ADD constraint EMPLEADOS_PERSONA_FK foreign key(COD_PERSONA)
references PERSONA(COD_PERSONA);

ALTER TABLE MENSAJE
ADD constraint MENSAJE_PERSONA_FK foreign key(COD_PERSONA)
references PERSONA(COD_PERSONA);

/*ALTER TABLE MENSAJE
ADD constraint MENSAJE_AMIGOS_FK foreign key(COD_AMIGO)
references AMIGOS(COD_AMIGO);*/

ALTER TABLE AMIGOS
ADD constraint AMIGOS_PERSONA_FK foreign key(COD_PERSONA)
references PERSONA(COD_PERSONA);

ALTER TABLE INTERESES_LABORALES
ADD constraint INTERESES_LABORALES_PERSONA_FK foreign key(COD_PERSONA)
references PERSONA(COD_PERSONA);